<style>
    #bot {
  margin: 50px 0;
  height: 700px;
  width: 550px;
  background: white;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 3px 3px 15px rgba(0, 0, 0, 0.2) ;
  border-radius: 20px;
  margin-left:100px;
}



/* Make container slightly rounded. Set height and width to 90 percent of .bots' */
#container {
  height: 90%;
  border-radius: 6px;
  width: 90%;
  background: #F3F4F6;
}


/* Style header section */
#header {
  width: 100%;
  height: 10%;
  border-radius: 6px;
  background: #3B82F6;
  color: white;
  text-align: center;
  font-size: 2rem;
  padding-top: 12px;
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.1);
}

/* Style body */
#body {
  width: 100%;
  height: 75%;
  background-color: #F3F4F6;
  overflow-y: auto;
 
}

/* Style container for user messages */
.userSection {
  width: 100%;
}



/* General styling for all messages */
.messages {
  max-width: 60%;
  margin: .5rem;
  font-size: 1.2rem;
  padding: .5rem;
  border-radius: 7px;
}

/* Targeted styling for just user messages */
.user-message {
  margin-top: 1rem;
  text-align: left;
  background: #3B82F6;
  color: white;
 
}



/* Style the input area */
textarea {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 84px;
  padding: 1rem;
  background: transparent;
  margin-bottom: 10px;
 
}

/* Style the text input */

/* Style send button */
#send {
    height: 32px;
 
    text-align: center;
    width: 20%;
    color: white;
    background: #3B82F6;
    cursor: pointer;
 
    border-radius: 6px;
 
    float: right;
    margin-bottom:20px;
  
}
    </style>
<?php
 $collection = $block->getThread();
 ?>
  <form class="form content"
      action="<?= $block->getUrl('chatbot/thread/save') ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
        <div id="bot">
            <div id="container">
                <div id="header">
                    Online Chatbot 
                </div>
                  <div id="body">
                    <table>
                      <?php 
                        foreach ($collection as $item): 
                      ?>
                        <tr>
                          <td>
                            <div class="userSection">
                              <div class="messages user-message">
                                <?php
                                echo $item['thread'];
                                ?>
                              </div>
                            </div>
                          </td>
                          <td>
                              <a href="<?= $block->escapeUrl($block->getChatUrl($item)) ?>" >
                              <span>View Chat</span>
                              </a>
                          </td>
                          <td>
                            <?php
                            if($item['approve']==2)
                            {
                              echo "cancelled";
                            }
                            else{
                            ?>
                              <a href="<?= $block->escapeUrl($block->getCancelUrl($item)) ?>" >
                              <span>Cancel</span>
                              </a>
                              <?php
                              }
                              ?>
                          </td>

                        </tr>
                      <?php endforeach;
                      ?>
                    </table>
                     
                  </div>
                    <div class="thread">
                        <textarea name="thread" id="thread" data-validate="{required:true}">
                        </textarea>
                    </div>
                    <div>
                        <button type="submit" id="send" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Submit')) ?>
                            </span>
                        </button>
                    </div>
            </div>
        </div>
  </form>

