<div class="field custom_age required">
   <label class="label" for="custom_age">
       <span>
            <?= $block->escapeHtml(__('Customer Age')) ?>
       </span>
   </label>
   <div class="control">
       <input type="text" name="custom_age" id="custom_age" value="" title="<?= $block->escapeHtmlAttr(__('Customer Age')) ?>" class="input-text" data-validate="{required:true}">
   </div>
</div>